name:  build-and-test
run-name: ${{ github.actor }} is building "${{ github.ref_name }}"
on: [push]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macos-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        if: runner.os == 'Linux'
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Download libampl
        run: python scripts/updatelib.py

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.12.0
        env:
          CIBW_ARCHS_LINUX: auto # aarch64 ppc64le
          CIBW_ARCHS_MACOS: x86_64 universal2
          CIBW_SKIP: pp* cp27-* *_i686 *-win32 *musllinux*
          CIBW_TEST_COMMAND: python -m amplpy.tests
          CIBW_TEST_REQUIRES: --index-url https://pypi.ampl.com --extra-index-url https://pypi.org/simple ampl_module_base ampl_module_minos pandas numpy

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl